---
- name: "Setup ipaserver"
  hosts: ipaserver
  become: yes
  
  tasks:
    - name: "Set a hostname for ipaserver"
      shell: hostnamectl set-hostname ipaserver.test.dom
  
    - name: "Ensure freeipa installed"
      apt:
        pkg:
        - astra-freeipa-server
        - fly-admin-freeipa-server
        state: present
        
    - name: Inititalize freeipa server
      shell: astra-freeipa-server -d test.local -p password -y -o 
      
    - name: Create users
      shell: ipa user-add user1 --first=u --last=p1
      shell: ipa user-add user2 --first=u --last=p2
