---
- name: "Sethostname for ipaserver"
  hosts: ipaserver
  become: yes

  tasks:
    - name: "Ensure tomcat installed"
      apt:
        pkg:
        - astra-freeipa-server
        - fly-admin-freeipa-server
        state: present
