---
- name: "Setup ipaserver"
  hosts: ipaserver
  become: yes
  
  task:
    - name: Set a hostname for ipaserver
      hostname:
        name: ipaserver.test.dom
  tasks:
    - name: "Ensure freeipa installed"
      apt:
        pkg:
        - astra-freeipa-server
        - fly-admin-freeipa-server
        state: present
