---
- name: "Setup ipaclient"
  hosts: ipaclient
  become: yes

  tasks:
    - name: "Set a hostname for ipaclient"
      shell: hostnamectl set-hostname ipaclient.test.local

    - name: "Ensure freeipa-client installed"
      apt:
        pkg:
        - astra-freeipa-client
        - fly-admin-freeipa-client
        - shared-mime-info
        - foreman-installer
        state: present

    - name: Adjust domain-controller as DNS
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 51.250.2.64'
        create: yes

    - name: Inititalize freeipa client
      shell: astra-freeipa-client -d test.local -y -u admin -p password
    
    - name: Add PTR record for Foreman
      ipa_dnsrecord:
        ipa_host: 51.250.2.64
        ipa_pass: password
        state: present
        zone_name: 0.128.10.in-addr.arpa.
        record_name: 11
        record_type: 'PTR'
        record_value: 'ipaclient.test.local'
        validate_certs: false


    - name: Initialize Foreman
      shell: foreman-installer
