---
- name: "Setup ipaclient"
  hosts: ipaclient
  become: yes

  tasks:
    - name: "Set a hostname for ipaclient"
      shell: hostnamectl set-hostname ipaclient.test.local

    - name: "Ensure freeipa-client installed"
      apt:
        pkg:
        - astra-freeipa-client
        - fly-admin-freeipa-client
        - shared-mime-info
        - foreman-installer
        state: present

    - name: Remove doamin configuration of yandex.cloud
      shell: echo " " > /etc/resolve.conf

    - name: Adjust domain-controller as DNS
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^(.*)nameserver(.*)$'
        line: 'nameserver 51.250.2.64'

    - name: Inititalize freeipa client
      shell: astra-freeipa-client -d test.local -y -u admin -p password

    - name: install ALD tools
      apt:
        pkg:
        - ald-client-common
        - ald-admin
        state: present

    - name: join domain 
      shell: ald-client join ipaserver.test.local --hostname ipaclient.test.local -f

    - name: Initialize Foreman
      shell: foreman-installer